services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"