service: lol-api

plugins:
  - serverless-offline
  - serverless-offline-watcher
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 3
  serverless-offline-watcher:
    - path:
        - functions/*.js
        - lib/*.js
        - lib/**/*.js
      command: echo "JS files were modified!"
  cors:
    origins: [
      'https://localhost:3000',
      'https://app.campeon.click',
    ]
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - api-lambda-auth
    allowCredentials: true
  lolAPISecrets: ${ssm:/aws/reference/secretsmanager/lol-api}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: ${opt:stage, 'development'}
  timeout: 25
  environment:
    APP_NAME: ${self:service}
    SECRETS_ID: lol-api
    IS_LOCAL: ${opt:isLocal, env:IS_LOCAL, false}
    CORS_ALLOW_ORIGIN: ${opt:corsAllowOrigin, env:CORS_ALLOW_ORIGIN, self:custom.lolAPISecrets.corsAllowOrigin}
    LAMBDA_AUTH_HEADER: ${opt:lambdaAuthHeader, env:LAMBDA_AUTH_HEADER, self:custom.lolAPISecrets.lambdaAuthHeader}
    LAMBDA_AUTH_HEADER_VALUE: ${opt:lambdaAuthHeaderValue, env:LAMBDA_AUTH_HEADER_VALUE, self:custom.lolAPISecrets.lambdaAuthHeaderValue}
    LOL_API_KEY: ${opt:lolApiKey, env:LOL_API_KEY, self:custom.lolAPISecrets.lolApiKey}
    LOL_API_ENDPOINT: ${opt:lolApiEndpoint, env:LOL_API_ENDPOINT, self:custom.lolAPISecrets.lolApiEndpoint}
    DATA_DRAGON_CDN: ${opt:dataDragonCdn, env:DATA_DRAGON_CDN, self:custom.lolAPISecrets.dataDragonCdn}
    CACHE_NAMESPACE: ${opt:cacheNamespace, env:CACHE_NAMESPACE, self:custom.lolAPISecrets.cacheNamespace}
    CACHE_REDIS_HOST: ${opt:redisHost, env:CACHE_REDIS_HOST, self:custom.lolAPISecrets.redisHost}
    MONGODB_URI: ${opt:mongodbUri, env:MONGODB_URI, self:custom.lolAPISecrets.mongodbUri}
    MONGODB_DBNAME: ${opt:mongodbDbName, env:MONGODB_DBNAME, self:custom.lolAPISecrets.mongodbDbName}
    MONGODB_COLLECTION_NAME: ${opt:mongodbDbCollectionName, env:MONGODB_COLLECTION_NAME, self:custom.lolAPISecrets.mongodbDbCollectionName}
  apiGateway:
    restApiId: ${opt:restApiId, self:custom.lolAPISecrets.restApiId, null}
    restApiRootResourceId: ${opt:restApiRootResourceId, self:custom.lolAPISecrets.restApiRootResourceId, null}
  iam:
    role: ${opt:defaultRoleArn, self:custom.lolAPISecrets.defaultRoleArn, null}
  vpc:
    subnetIds:
      'Fn::Split':
        - ','
        - ${opt:defaultSubnetIds, self:custom.lolAPISecrets.defaultSubnetIds, ''}
    securityGroupIds:
      'Fn::Split':
        - ','
        - ${opt:defaultSecurityGroupIds, self:custom.lolAPISecrets.defaultSecurityGroupIds, ''}

functions:
  helloWorld:
    handler: functions/hello-world.handler
    events:
      - http:
          path: /hello
          method: get
          cors: ${self:custom.cors}
  getByRiotId:
    handler: functions/get-by-riot-id.handler
    events:
      - http:
          path: /by-riot-id
          method: get
          cors: ${self:custom.cors}
  getSummonerChampions:
    handler: functions/get-summoner-champions.handler
    events:
      - http:
          path: /get-summoner-champions
          method: get
          cors: ${self:custom.cors}
  getSummonerDetails:
    handler: functions/get-summoner-details.handler
    events:
      - http:
          path: /get-summoner-details
          method: get
          cors: ${self:custom.cors}
  getChampions:
    handler: functions/get-champions.handler
    events:
      - http:
          path: /get-champions
          method: get
          cors: ${self:custom.cors}
