version: '3'
services:
  mysql:
    image: postgres:12.2-alpine
    restart: always
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "gsparedes"
      POSTGRES_PASSWORD: "dbpassword"
    volumes:
    - ./docker-entrypoint-initdb.d/docker-entrypoint-initdb.d
  elasticsearch:
    image: elasticsearch:7.7.1
    restart: always
    container_name: elasticsearch
    environment:
      - node.name=master
      - cluster.name=lolstats-cluster
      - cluster.initial_master_nodes=master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  esdata:
